// This file was generated by resx2srid

namespace System.Windows
{
partial class SRID
{
    public const string Host_CannotRotateWindowsFormsHost = "Host_CannotRotateWindowsFormsHost";
    public const string Host_ChildCantBeTopLevelForm = "Host_ChildCantBeTopLevelForm";
    public const string WFI_ArgumentNullOrEmpty = "WFI_ArgumentNullOrEmpty";
    public const string WFI_NullArgument = "WFI_NullArgument";
    public const string WFI_PropertyDoesntExist = "WFI_PropertyDoesntExist";
    public const string WFI_PropertyMapError = "WFI_PropertyMapError";
    public const string WFI_PropertyMappingExists = "WFI_PropertyMappingExists";
}
}
