// This file was generated by resx2srid

namespace MS.Internal.Automation
{
partial class SR
{
    public const string ElementNotAvailable = "ElementNotAvailable";
    public const string ElementNotEnabled = "ElementNotEnabled";
    public const string LocalizedControlTypeButton = "LocalizedControlTypeButton";
    public const string LocalizedControlTypeCalendar = "LocalizedControlTypeCalendar";
    public const string LocalizedControlTypeCheckBox = "LocalizedControlTypeCheckBox";
    public const string LocalizedControlTypeComboBox = "LocalizedControlTypeComboBox";
    public const string LocalizedControlTypeCustom = "LocalizedControlTypeCustom";
    public const string LocalizedControlTypeDataGrid = "LocalizedControlTypeDataGrid";
    public const string LocalizedControlTypeDataItem = "LocalizedControlTypeDataItem";
    public const string LocalizedControlTypeDocument = "LocalizedControlTypeDocument";
    public const string LocalizedControlTypeEdit = "LocalizedControlTypeEdit";
    public const string LocalizedControlTypeGroup = "LocalizedControlTypeGroup";
    public const string LocalizedControlTypeHeader = "LocalizedControlTypeHeader";
    public const string LocalizedControlTypeHeaderItem = "LocalizedControlTypeHeaderItem";
    public const string LocalizedControlTypeHyperlink = "LocalizedControlTypeHyperlink";
    public const string LocalizedControlTypeImage = "LocalizedControlTypeImage";
    public const string LocalizedControlTypeListItem = "LocalizedControlTypeListItem";
    public const string LocalizedControlTypeListView = "LocalizedControlTypeListView";
    public const string LocalizedControlTypeMenu = "LocalizedControlTypeMenu";
    public const string LocalizedControlTypeMenuBar = "LocalizedControlTypeMenuBar";
    public const string LocalizedControlTypeMenuItem = "LocalizedControlTypeMenuItem";
    public const string LocalizedControlTypePane = "LocalizedControlTypePane";
    public const string LocalizedControlTypeProgressBar = "LocalizedControlTypeProgressBar";
    public const string LocalizedControlTypeRadioButton = "LocalizedControlTypeRadioButton";
    public const string LocalizedControlTypeScrollBar = "LocalizedControlTypeScrollBar";
    public const string LocalizedControlTypeSeparator = "LocalizedControlTypeSeparator";
    public const string LocalizedControlTypeSlider = "LocalizedControlTypeSlider";
    public const string LocalizedControlTypeSpinner = "LocalizedControlTypeSpinner";
    public const string LocalizedControlTypeSplitButton = "LocalizedControlTypeSplitButton";
    public const string LocalizedControlTypeStatusBar = "LocalizedControlTypeStatusBar";
    public const string LocalizedControlTypeTab = "LocalizedControlTypeTab";
    public const string LocalizedControlTypeTabItem = "LocalizedControlTypeTabItem";
    public const string LocalizedControlTypeTable = "LocalizedControlTypeTable";
    public const string LocalizedControlTypeText = "LocalizedControlTypeText";
    public const string LocalizedControlTypeThumb = "LocalizedControlTypeThumb";
    public const string LocalizedControlTypeTitleBar = "LocalizedControlTypeTitleBar";
    public const string LocalizedControlTypeToolBar = "LocalizedControlTypeToolBar";
    public const string LocalizedControlTypeToolTip = "LocalizedControlTypeToolTip";
    public const string LocalizedControlTypeTreeView = "LocalizedControlTypeTreeView";
    public const string LocalizedControlTypeTreeViewItem = "LocalizedControlTypeTreeViewItem";
    public const string LocalizedControlTypeWindow = "LocalizedControlTypeWindow";
}
}
