// This file was generated by resx2srid

namespace MS.Internal.Automation
{
partial class SRID
{
    public const string GenericInvalidArgument = "GenericInvalidArgument";
    public const string HwndMustBeNonNULL = "HwndMustBeNonNULL";
}
}
