// This file was generated by resx2srid

namespace Microsoft.Windows.Controls
{
partial class SRID
{
    public const string ElementNotKeyTipScope = "ElementNotKeyTipScope";
    public const string InRibbonGallery_ScrollDownButtonAutomationName = "InRibbonGallery_ScrollDownButtonAutomationName";
    public const string InRibbonGallery_ScrollUpButtonAutomationName = "InRibbonGallery_ScrollUpButtonAutomationName";
    public const string InvalidApplicationMenuOrItemContainer = "InvalidApplicationMenuOrItemContainer";
    public const string InvalidCtorParameterNoInfinityForStarSize = "InvalidCtorParameterNoInfinityForStarSize";
    public const string InvalidCtorParameterNoNaN = "InvalidCtorParameterNoNaN";
    public const string InvalidCtorParameterUnknownRibbonControlLengthUnitType = "InvalidCtorParameterUnknownRibbonControlLengthUnitType";
    public const string InvalidKeyTipOffset = "InvalidKeyTipOffset";
    public const string InvalidMenuButtonOrItemContainer = "InvalidMenuButtonOrItemContainer";
    public const string QATKeyTipCharacters = "QATKeyTipCharacters";
    public const string ResizeParametersNotValid = "ResizeParametersNotValid";
    public const string RibbonContextMenu_AddGalleryToQAT = "RibbonContextMenu_AddGalleryToQAT";
    public const string RibbonContextMenu_AddToQAT = "RibbonContextMenu_AddToQAT";
    public const string RibbonContextMenu_MaximizeTheRibbon = "RibbonContextMenu_MaximizeTheRibbon";
    public const string RibbonContextMenu_MinimizeTheRibbon = "RibbonContextMenu_MinimizeTheRibbon";
    public const string RibbonContextMenu_RemoveFromQAT = "RibbonContextMenu_RemoveFromQAT";
    public const string RibbonContextMenu_ShowQATAbove = "RibbonContextMenu_ShowQATAbove";
    public const string RibbonContextMenu_ShowQATBelow = "RibbonContextMenu_ShowQATBelow";
    public const string RibbonGallery_AllFilter = "RibbonGallery_AllFilter";
    public const string RibbonGroupsPanel_InvalidRegistrationParameter = "RibbonGroupsPanel_InvalidRegistrationParameter";
    public const string RibbonQuickAccessToolBar_OverflowButtonToolTip = "RibbonQuickAccessToolBar_OverflowButtonToolTip";
    public const string RibbonWindow_ExtendUnShownGlass = "RibbonWindow_ExtendUnShownGlass";
    public const string Ribbon_ContextualTabHeadersSourceInvalid = "Ribbon_ContextualTabHeadersSourceInvalid";
    public const string SetFocusFailed = "SetFocusFailed";
    public const string UIA_OperationCannotBePerformed = "UIA_OperationCannotBePerformed";
    public const string VirtualizedElement = "VirtualizedElement";
}
}
