// This file was generated by resx2srid

namespace System
{
partial class SRID
{
    public const string Assembly0NotFound = "Assembly0NotFound";
    public const string AtLeastOnePropertyMustBeSpecified = "AtLeastOnePropertyMustBeSpecified";
    public const string CachedPropertyNotRequested = "CachedPropertyNotRequested";
    public const string CacheReqestCanOnlyPopTop = "CacheReqestCanOnlyPopTop";
    public const string CacheReqestCantModifyWhileActive = "CacheReqestCantModifyWhileActive";
    public const string CacheRequestNeedCache = "CacheRequestNeedCache";
    public const string CacheRequestNeedElementReference = "CacheRequestNeedElementReference";
    public const string CacheRequestNeedLiveForProperties = "CacheRequestNeedLiveForProperties";
    public const string CantPrefetchTextPattern = "CantPrefetchTextPattern";
    public const string CouldNotFindRegisterMethodOnType0InAssembly1 = "CouldNotFindRegisterMethodOnType0InAssembly1";
    public const string CouldNotFindType0InAssembly1 = "CouldNotFindType0InAssembly1";
    public const string EventIdMustNotBeAutomationFocusChanged = "EventIdMustNotBeAutomationFocusChanged";
    public const string EventIdMustNotBeAutomationPropertyChanged = "EventIdMustNotBeAutomationPropertyChanged";
    public const string EventIdMustNotBeStructureChanged = "EventIdMustNotBeStructureChanged";
    public const string GenericInvalidArgument = "GenericInvalidArgument";
    public const string HwndMustBeNonNULL = "HwndMustBeNonNULL";
    public const string IgnoreCaseRequiresString = "IgnoreCaseRequiresString";
    public const string LogicalElementNoClickablePoint = "LogicalElementNoClickablePoint";
    public const string MustBeAtLeastTwoConditions = "MustBeAtLeastTwoConditions";
    public const string NonclientClassnameCannotBeUsedWithFlagsOrImagename = "NonclientClassnameCannotBeUsedWithFlagsOrImagename";
    public const string OperationCannotBePerformed = "OperationCannotBePerformed";
    public const string ParamsNotApplicableToWindowClosedEvent = "ParamsNotApplicableToWindowClosedEvent";
    public const string PropertyConditionIncorrectType = "PropertyConditionIncorrectType";
    public const string ScreenCoordinatesOutsideBoundingRect = "ScreenCoordinatesOutsideBoundingRect";
    public const string SetFocusFailed = "SetFocusFailed";
    public const string TextAttributeValueWrongType = "TextAttributeValueWrongType";
    public const string TextMustNotBeNullOrEmpty = "TextMustNotBeNullOrEmpty";
    public const string TreeScopeElementChildrenDescendantsOnly = "TreeScopeElementChildrenDescendantsOnly";
    public const string TreeScopeNeedAtLeastOne = "TreeScopeNeedAtLeastOne";
    public const string UnexpectedWindowState = "UnexpectedWindowState";
    public const string UnknownCoreAPIError = "UnknownCoreAPIError";
    public const string UnsupportedAttribute = "UnsupportedAttribute";
    public const string UnsupportedPattern = "UnsupportedPattern";
    public const string UnsupportedProperty = "UnsupportedProperty";
    public const string ValueReadonly = "ValueReadonly";
}
}
