//
// This file was generated by resx2sr tool
//

partial class SR
{
	public const string ArgumentOutOfRange = "Value of {0} is outside of the allowed range.";
	public const string CannotChangeParameterDuringInertia = "The value of {0} cannot be changed while the inertia processor is running.";
	public const string IllegalPivotRadius = "Value of {0} must be either NaN, or a finite value greater than or equal to 1.";
	public const string InertiaParametersUnspecified1and2 = "Either {0}, or {1} and {2}, needs to be specified.";
	public const string InertiaParametersUnspecified2 = "Either {0} or {1} needs to be specified.";
	public const string InertiaProcessorInvalidRadius = "InitialRadius should be a finite number, greater than or equal to 1.";
	public const string InvalidTimestamp = "Timestamp values must not decrease.";
	public const string NoInertiaVelocitiesSpecified = "At least one of the following must be specified: linear velocity ({0} or {1}), angular velocity ({2}), or expansion velocity ({3} or {4}).";
	public const string OnlyProportionalExpansionSupported = "Currently, only proportional expansion is supported. {0} must equal {1}."; // {entry.Item3}
	public const string ValueMustBeFinite = "Value of {0} must be finite.";
	public const string ValueMustBeFiniteNonNegative = "Value of {0} must be finite and non-negative.";
	public const string ValueMustBeFiniteOrNaN = "Value of {0} must be finite or NaN.";
}
